### PR TITLE
implement readme, aip template, and draft aip-1

### PR DESCRIPTION
**Pull request by ZakkMan**
This PR implements a draft, first pass of the readme for this repository,
template for future AIPs, and AIP-1, which outlines the overall AIP process.

The contents of this PR are heavily inspired by the following sources:

- [Ethereum Improvement Proposals](https://github.com/ethereum/EIPs/tree/master)
- [Aave Improvement Proposals](https://github.com/aave/aip)
- [Python Enhancement Proposals](https://peps.python.org/)
- [csharplang](https://github.com/dotnet/csharplang)

### CODE REVIEW

**Review by thelostone-mc — APPROVED** [review]
LGTM.

The lifecycle does seem complex to start off with but we can throw up a Meta AIP

**Comment by thelostone-mc** [comment]
> Is there anything that looks unnecessary right off the bat?

Maybe the withdraw state! But down the line, I can see why that's useful

**Comment by ZakkMan** [comment]
@hmrtn will you have a chance to review and provide feedback soon?

@thelostone-mc - anyone else we want to get input from?

**Comment by codenamejason** [comment]
This looks great @ZakkMan 🙌 I think the initial complexity may be necessary to weed out people throwing up AIP's without being thorough.

**Review by codenamejason — APPROVED** [review]

**Review by gravityblast — APPROVED** [review]

**Pull request merged**
